### ISSUE TITLE
Problem with autoload

### ISSUE THREAD

**Issue by tollerm** [emacs-helm/helm-recoll#12] opened 2016-05-28 08:47 UTC
When configuring the emacs init file using use-package as

(use-package helm-recoll
:ensure t
:defer t
:config
(helm-recoll-create-source "main" "~/.recoll"))

helm-recoll triggers the loading of the helm file while the helm loading should be delayed in this configuration. Please, see the relevant discussion at the helm page: 
https://github.com/emacs-helm/helm/issues/1519

**Comment by michael-heerdegen** [comment] 2016-05-28 20:34
Thanks @tollerm.

@csantosb the cause is the
```
(require 'helm-mode)
```
call in the macro `helm-recoll-create-source`.  Do you recall why you had put it there?  It seems it was introduced by accident in the commit where you corrected the line end conventions.

If loading `helm-mode` is necessary to use this package, we should probably call it at top level.

Thanks,

Michael.

**Comment by csantosb** [comment] 2016-05-30 19:37
You're right. We should probably remove this line, no need to call it at all. I just tested and things run fine without.

**Comment by michael-heerdegen** [comment] 2016-06-01 22:51
I've done that now.

@tollerm Please check if everything is alright now.  And also note: when you call `helm-recoll-create-source`, there is a command defined and a source.  Calling the command should always work, but if you want to use the source, you _must_ require helm-recoll before.  If you don't require it, the source will be non-existent.  This is the best I can do: defining the source requires too many things from "helm-recoll.el".  To avoid loading the file when loading the init file, I delay the definition of the source until "helm-recoll" has been loaded (with `with-eval-after-load`).  The defined command OTOH can arrange to do this by itself.

So this is a compromise.  Adding even more magic would complicate the code unnecessarily I think, because when you make use of the defined source in code in your init file, you can add the require call by yourself.

Is this acceptable?  I guess I should add a note about that in the documentation...

**Comment by tollerm** [comment] 2016-06-02 09:30
Unfortunately, it did not help me. I still have loading helm-recoll. Because helm-recoll-create-source is a macro, it is eager expanded during loading init.el file that results in subsequent loading helm-recoll and helm. The best solution would be to rewrite helm-recoll-create-source as a function but it requires too much work. Let's keep everything as it is now. Anyhow I need helm mainly directly after startup and some extra loading time (1-2 seconds) is not important.

**Comment by tollerm** [comment] 2016-06-02 17:06
If helm-recoll-create was a function, its loading could be defered by the use-package as it happens with all other packages except the helm-recoll. I don't want to compile my init.el file because I always forget to recompile it after making changes what I do quite often. Also compilation does not play very well with the use-package.
Actually I do not understand the necessity of producing multiple sources helm-recoll-someextension in runtime. I do not think that anybody is using more than one source.

**Comment by michael-heerdegen** [comment] 2016-06-02 19:57
tollerm <notifications@github.com> writes:

> If helm-recoll-create was a function, its loading could be defered by
> the use-package as it happens with all other packages except the
> helm-recoll.

Why can't this be done for macros as well?  A simple
`with-eval-after-load' call would be able do handle that.

> Actually I do not understand the necessity of producing multiple
> sources helm-recoll-someextension in runtime. I do not think that
> anybody is using more than one source.

Dunno how many people are using this feature.  What's the problem with
it?


BTW, you don't need `helm-recoll-create-source' to create a source.
There is a class `helm-recoll-source' defined, so you can also simply
call `helm-make-source' to create a source as usual.
`helm-recoll-create-source' is only handy if you want to define a
command along with the source.

**Comment by michael-heerdegen** [comment] 2016-06-02 20:59
Michael Heerdegen <michael_heerdegen@web.de> writes:

> Dunno how many people are using this feature.  What's the problem with
> it?

But of course could we add one or two user options for specifying the
data for a default source, and add an autoloaded command that starts a
helm session for this default source.  That would make things easier for
most people and avoid the problem of this report entirely.

**Comment by tollerm** [comment] 2016-06-03 06:43
> Why can't this be done for macros as well? A simple `with-eval-after-load' call would be able do handle that.

How "with-eval -after-load" can help? The macro is always expanded. It comes again that "with-eval-after-load" should be changed. Furthermore, as a user I expect that code snippet with which I started this thread should work for all packages. And it works for all packages except helm-recoll. Why  should a user provide workarounds for this package?
>But of course could we add one or two user options for specifying the data for a default source, and add an autoloaded command that starts a helm session for this default source

It would be very nice. As I can recollect, recoll makes only one index which is saved in the directory '~/.recoll' and thus the necessity of making other sources for recoll is not clear for me.

**Comment by thierryvolpiatto** [comment] 2016-06-03 06:54
@michael-heerdegen 
Why is this complication with `with-eval-after-load` and further `defvar` ?
AFAIU the source you are declaring with defvar inside the macro is used only in the command you are also defining, so why not just building the source at runtime? i.e putting the `helm-make-source` inside the `:sources` slot directly.

**Comment by michael-heerdegen** [comment] 2016-06-03 14:15
Thierry Volpiatto <notifications@github.com> writes:

> @michael-heerdegen Why is this complication with with-eval-after-load
> and further defvar ?  AFAIU the source you are declaring with defvar
> inside the macro is used only in the command you are also defining, so
> why not just building the source at runtime?

No, it's also used in the "helm-recoll-sources" meta source.

Apart from that, some people may want to use the source in their own
stuff and don't need the defined command at all.

**Comment by thierryvolpiatto** [comment] 2016-06-03 14:30
This defeat completely the purpose of autoloads, I have created #14 that load helm-recoll and create commands and source as soon as `helm-recoll` is called, this is the right thing to do IMO.
Calling `helm-recoll-create-sources` as a macro containing `with-eval-after-load`+`defvar` and assuming user compile its init file is plain wrong IMO.

Here the `use-package` config:

```elisp
(use-package helm-recoll
    :commands helm-recoll
    :init (setq helm-recoll-directories
                '(("confdir" . "~/.recoll-.emacs.d")
                  ("lisp sources" . "~/.recoll-elisp")
                  ("work" . "~/.recoll-work"))))
```
Thus it seems the API have changed and figuring out how to create the db took me some time, this should be configured in README, I have added instructions in source file only for now. 

Also having to call `helm-recoll-create-sources` from init file is not convenient, the PR #14 is fixing this with a simple defcustom, the user just have to configure it via the customize interface or in `:init`
slot of use-package like in the snippet above.

**Comment by michael-heerdegen** [comment] 2016-06-03 14:36
tollerm <notifications@github.com> writes:

> How "with-eval-after-load" can help? The macro is always expanded.

With `with-eval-after-load' the macro is not expanded before you load
"helm-recoll".

> It comes again that "with-eval-after-load" should be
> changed. Furthermore, as a user I expect that code snippet with which
> I started this thread should work for all packages. And it works for
> all packages except helm-recoll. Why should a user provide workarounds
> for this package?

`use-package' obviously doesn't handle macros in a reasonable way.  This
is not my fault.  I won't code around use-package's deficiencies and
make the code worse for people not using use-package.

> It would be very nice. As I can recollect, recoll makes only one index
> which is saved in the directory '~/.recoll'

You can manage to have an arbitrary number of indexes.

> and thus the necessity of making other sources for recoll is not clear
> for me.

See the recoll docs, e.g.

http://www.lesbonscomptes.com/recoll/usermanual/webhelp/docs/RCL.INDEXING.INTRODUCTION.CONFIG.html

**Comment by michael-heerdegen** [comment] 2016-06-03 15:18
Thierry Volpiatto <notifications@github.com> writes:

> This defeat completely the purpose of autoloads, I have created #14

Thanks.

> that load helm-recoll and create commands and source as soon as
> helm-recoll is called, this is the right thing to do IMO.

> Calling helm-recoll-create-sources as a macro containing
> with-eval-after-load+defvar and assuming user compile its init file is
> plain wrong IMO.

I don't assume it, but if you do it, you have the usual advantages.  If
you don't, you can still simply use `with-eval-after-load', and that's
it.

> Here the use-package config:
>
> (use-package helm-recoll
>     :commands helm-recoll
>     :init (setq helm-recoll-directories
>                 '(("confdir" . "~/.recoll-.emacs.d")
>                   ("lisp sources" . "~/.recoll-elisp")
>                   ("work" . "~/.recoll-work"))))

Well, what you suggest is optimal for users of use-package, but a huge
regression for all others.

Now, anybody customizing helm-recoll-directories will have to load the
package unconditionally when starting Emacs.


Optimizing the thing for `use-package' and ignoring the rest is not the
way to go IMHO.  Your PR includes interesting approaches OTOH, let me
think about it, but I don't want to merge it as is.

**Comment by thierryvolpiatto** [comment] 2016-06-03 15:36
Michael Heerdegen <notifications@github.com> writes:

> Well, what you suggest is optimal for users of use-package, but a huge
> regression for all others.

Absolutely not.

> Now, anybody customizing helm-recoll-directories will have to load the
> package unconditionally when starting Emacs.

No:

add to init file:

    (setq helm-recoll-directories '(("confdir" . "~/.recoll-.emacs.d")
                                    ("lisp sources" . "~/.recoll-elisp")
                                    ("work" . "~/.recoll-work")))
    (autoload 'helm-recoll "helm-recoll.el" nil t)

That's all, no need of use-package, everything is created/loaded only
once M-x helm-recoll is called.

NOTE: Even better is to set helm-recoll-directories with customize interface.

> Optimizing the thing for `use-package' and ignoring the rest is not the
> way to go IMHO.

Agree.

-- 
Thierry

**Comment by michael-heerdegen** [comment] 2016-06-03 15:51
Thierry Volpiatto <notifications@github.com> writes:

> NOTE: Even better is to set helm-recoll-directories with customize
> interface.

That's what I mean: the special setter you use is only available after
loading the package, no?

**Comment by thierryvolpiatto** [comment] 2016-06-03 16:43
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> NOTE: Even better is to set helm-recoll-directories with customize
>> interface.
>
> That's what I mean: the special setter you use is only available after
> loading the package, no?

The point is not loading helm-recoll and helm when loading the init
file, right ?
So the special set function will run only when you call helm-recoll.

What is the problem ?

-- 
Thierry

**Comment by tollerm** [comment] 2016-06-03 17:24
Michael Heerdegen <notifications@github.com> writes:
> `use-package' obviously doesn't handle macros in a reasonable way. This is not my fault. I won't code around use-package's deficiencies and make the code worse for people not using use-package.

No, use-package handles macro's in a correct way. At present time, even without use-package helm-recoll is always loaded if somewhere in init.el file helm-recoll-create-source is present.

> You can manage to have an arbitrary number of indexes.
 See the recoll docs, e.g.

Thank you for the reference. I never had any reason to use this feature and it's added value is not clear for me. You can always restrict your search in query to a desired directory, don't you? 

Anyhow, the solution of Thierry is very suitable for me.

**Comment by michael-heerdegen** [comment] 2016-06-03 18:34
tollerm <notifications@github.com> writes:

> No, use-package handles macro's in a correct way. At present time,
> even without use-package helm-recoll is always loaded if somewhere in
> init.el file helm-recoll-create-source is present.

Not if you use "with-eval-after-load" as I suggested - this is the
standard way to delay loading a package and configure it nonetheless.

**Comment by michael-heerdegen** [comment] 2016-06-03 18:36
Thierry Volpiatto <notifications@github.com> writes:

> > That's what I mean: the special setter you use is only available
> > after loading the package, no?
>
> The point is not loading helm-recoll and helm when loading the init
> file, right ?

Yes.

> So the special set function will run only when you call helm-recoll.

The custom setter function will be called when loading your custom file,
or when calling "customize-set-variable" from your init file.  I.e. when
loading Emacs.

**Comment by thierryvolpiatto** [comment] 2016-06-03 18:37
Michael Heerdegen <notifications@github.com> writes:

> tollerm <notifications@github.com> writes:
>
>> No, use-package handles macro's in a correct way. At present time,
>> even without use-package helm-recoll is always loaded if somewhere in
>> init.el file helm-recoll-create-source is present.
>
> Not if you use "with-eval-after-load" as I suggested - this is the
> standard way to delay loading a package and configure it nonetheless.

Not inside a macro, with-eval-after-load is intended to be used at the
user configuration level, not inside code.

   Normally, well-designed Lisp programs should not use
‘eval-after-load’.  If you need to examine and set the variables defined
in another library (those meant for outside use), you can do it
immediately—there is no need to wait until the library is loaded.  If
you need to call functions defined by that library, you should load the
library, preferably with ‘require’ (*note Named Features::).

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-06-03 18:47
Michael Heerdegen <notifications@github.com> writes:

> Thierry Volpiatto <notifications@github.com> writes:
>
>> > That's what I mean: the special setter you use is only available
>> > after loading the package, no?
>>
>> The point is not loading helm-recoll and helm when loading the init
>> file, right ?
>
> Yes.
>
>> So the special set function will run only when you call helm-recoll.
>
> The custom setter function will be called when loading your custom file,
> or when calling "customize-set-variable" from your init file. I.e. when
> loading Emacs.

NO!!! Only when you call helm-recoll, not before.

-- 
Thierry

**Comment by thierryvolpiatto** [comment] 2016-06-03 18:49
I give up, do what you want.

-- 
Thierry

**Comment by michael-heerdegen** [comment] 2016-06-03 18:55
Thierry Volpiatto <notifications@github.com> writes:

> Normally, well-designed Lisp programs should not use
> ‘eval-after-load’. If you need to examine and set the variables
> defined in another library (those meant for outside use), you can do
> it immediately—there is no need to wait until the library is
> loaded.

Well, in our case, we want to construct a source from within the init
file, which is a bit more than setting some variables.  That's why I was
suggesting to introduce user options to specify a default source.

> If you need to call functions defined by that library, you should load
> the library, preferably with ‘require’ (*note Named Features::).

We can could use the approach you suggested, but only without the
problematic custom setter function.  Then it's the same as I suggested:
introduce options to define the basic data for the default sourc(es).

**Comment by michael-heerdegen** [comment] 2016-06-03 19:06
Thierry Volpiatto <notifications@github.com> writes:

> Not inside a macro, with-eval-after-load is intended to be used at the
> user configuration level, not inside code.

The expansion of the macro _is_ the user configuration code.  It's a
shortcut for the user to spare him to write the same lines into his
config file.  That's why it's a macro.  But yes, you must compile your
init file to avoid the direct dependency on the package.  If you don't
want to compile it, you could still use "with-eval-after-load" in your
init file, and call the thing from there.  That's why I chose this
solution.

**Comment by michael-heerdegen** [comment] 2016-06-03 19:23
Thierry Volpiatto <notifications@github.com> writes:

> NO!!! Only when you call helm-recoll, not before.

You are right, customize does now save an unevaluated expression.

> I give up, do what you want.

But instead of just telling me that in one sentence, you are getting
rude.  I'll not accept that.

**Comment by michael-heerdegen** [comment] 2016-06-05 21:26
Merged.  Thanks everybody.

**Closed by michael-heerdegen** 2016-06-05 21:26 UTC
